version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - VECTOR_DB=milvus  # or milvus, pinecone, weaviate
    volumes:
      - .:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./webui
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - app-network

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge