version: '3'
services:
  milvus-standalone:
    mem_limit: 4g
    mem_reservation: 3g
    image: milvusdb/milvus:v2.4.1
    container_name: milvus-standalone
    security_opt:
      - seccomp:unconfined
    environment:
      - MILVUS_LOG_LEVEL=debug
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd
      - ETCD_CONFIG_PATH=/milvus/configs/embedEtcd.yaml
      - COMMON_STORAGETYPE=local
    volumes:
      - /Users/mg/mg-work/manav/work/ai-experiments/rag_modulo/volumes/milvus:/var/lib/milvus
      - ./embedEtcd.yaml:/milvus/configs/embedEtcd.yaml
    ports:
      - "19530:19530"
      - "9091:9091"
      - "2379:2379"
    command: ["milvus", "run", "standalone"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 90s
